"""Custom tools for CinemaForge agents.

Each tool is a plain function — ADK auto-wraps them as FunctionTool.
Docstrings become the tool description the LLM sees."""

import json
import time
from typing import Optional

from . import metrics


def analyze_content_performance(
    topic: str,
    time_range: str = "7d",
) -> str:
    """Query production analytics to see how content on a given topic has
    performed historically. Returns views, watch time, retention, and CTR
    for similar past productions.

    Args:
        topic: The content topic to analyze (e.g. "anxiety", "motivation").
        time_range: How far back to look (e.g. "7d", "28d", "90d").
    """
    metrics.tool_calls.add(1, {"tool": "analyze_content_performance"})
    start = time.time()
    # In production this queries Grafana via MCP. For the demo, return
    # realistic data shaped like what a real analytics backend would give.
    data = {
        "topic": topic,
        "time_range": time_range,
        "similar_videos_found": 8,
        "avg_views": 342,
        "avg_watch_time_hours": 4.7,
        "avg_retention_pct": 38.2,
        "avg_ctr_pct": 2.4,
        "top_performing_angle": "personal-story hook with emotional resolution",
        "worst_performing_angle": "listicle format with generic advice",
        "audience_peak_hours_utc": [20, 21, 22, 3, 4],
        "recommendation": (
            f"Content about '{topic}' performs best with a personal-story "
            f"hook. Avoid listicle framing. Schedule for evening/night hours "
            f"(20:00-22:00 UTC) when the target audience is winding down."
        ),
    }
    metrics.tool_duration.record(time.time() - start, {"tool": "analyze_content_performance"})
    return json.dumps(data, indent=2)


def generate_scene_descriptions(
    script: str,
    style: str = "cinematic",
    num_scenes: int = 6,
) -> str:
    """Break a script into visual scenes with detailed image-generation
    prompts. Each scene gets a description suitable for AI image generation.

    Args:
        script: The full script text to visualize.
        style: Visual style (cinematic, documentary, animated, noir).
        num_scenes: Number of scenes to generate.
    """
    metrics.tool_calls.add(1, {"tool": "generate_scene_descriptions"})
    start = time.time()
    scenes = []
    for i in range(num_scenes):
        scenes.append({
            "scene_number": i + 1,
            "timestamp": f"{i * 20}s - {(i + 1) * 20}s",
            "visual_prompt": (
                f"Scene {i+1} of {num_scenes}, {style} style. "
                "Detailed visual description would be generated by the "
                "Director agent based on the script content at this point."
            ),
            "camera": ["wide establishing", "medium close-up", "slow dolly", "aerial", "tight close-up", "tracking"][i % 6],
            "lighting": "warm golden hour" if i < 3 else "cool blue evening",
            "mood": "hopeful" if i % 2 == 0 else "contemplative",
        })
    result = {"scenes": scenes, "style": style, "thumbnail_concept": (
        f"High-contrast {style} frame from scene 1 with bold text overlay. "
        "Face or strong emotion visible. Rule of thirds composition."
    )}
    metrics.tool_duration.record(time.time() - start, {"tool": "generate_scene_descriptions"})
    return json.dumps(result, indent=2)


def optimize_metadata(
    title: str,
    description: str,
    topic: str,
    target_audience: str,
) -> str:
    """Optimize video metadata (title, description, tags) for discovery.
    Uses SEO best practices and performance data patterns.

    Args:
        title: Draft video title.
        description: Draft video description.
        topic: The main topic/theme.
        target_audience: Who this video is for.
    """
    metrics.tool_calls.add(1, {"tool": "optimize_metadata"})
    start = time.time()
    result = {
        "optimized_title": title,
        "title_notes": "Title should be under 60 chars, lead with emotion, include the core keyword.",
        "tags": [topic, target_audience, "motivation", "self-improvement", "mindset"],
        "category": "Entertainment",
        "default_language": "en",
        "scheduling_recommendation": "Publish at 20:00 UTC for maximum reach in US/EU evening hours.",
    }
    metrics.tool_duration.record(time.time() - start, {"tool": "optimize_metadata"})
    return json.dumps(result, indent=2)


def log_production_event(
    stage: str,
    status: str,
    details: Optional[str] = None,
) -> str:
    """Log a production pipeline event for monitoring in Grafana.

    Args:
        stage: Pipeline stage (research, writing, directing, seo).
        status: Event status (started, completed, error).
        details: Optional details about the event.
    """
    metrics.production_events.add(1, {"stage": stage, "status": status})
    return json.dumps({"logged": True, "stage": stage, "status": status})
